# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16qP7Hp9JFNAWzn7Sag_UGeKYHXuaZkLI
"""

a,b=10,5
print(a+b)