# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18uObvbUhNDyk6QUSmGUsUXJUV95Mt-v4
"""

n=7
print(n*n)
