# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16VKD1NtU0HHzugsnzGxwcDNyN8RVPWZI
"""

name=bhavya
print(name)